### ISSUE TITLE
New delta function has fix_symmetry set to "False"

### ISSUE THREAD

**Issue by andbue** [cophi-wue/pydelta#2]
If a new CompositeDeltaFunction is created, its fix_symmetry-attribute is for some reason set to "False".
Is this the expected behaviour?

**Comment by thvitt** [comment]
I don't quite get your question … `fix_symmetry` is a property of MetricDeltaFunction (which encapsulates a distance metric like those from scikit-learn), and it is only used in MetricDeltaFunction's `__call__` method. CompositeDeltaFunction simply delegates to an existing (possibly Metric) DeltaFunction.

(In other words: Could you provide a problematic test case?)

**Comment by thvitt** [comment]
I still can't reproduce this. Here's a test:

https://github.com/cophi-wue/pydelta/blob/f9e12b0d0e32d49c66dee735fea09bae284f0f84/test/deltas_test.py#L58-L63

**Comment by andbue** [comment]
Sorry, after restarting my jupyter kernel it works as expected. Must have been my own code's fault.
Thanks for looking into this issue anyway!
